name: Release
on:
  push
jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable
      - name: 缓存 Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: 安装node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: 安装pnpm
        run: npm i -g pnpm
      - name: 安装依赖
        run: pnpm install

      - name: 打包
        uses: tauri-apps/tauri-action@v0.5.19

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'TTVVL v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version'
          releaseDraft: false
          prerelease: false
          publish: true